homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_timezone
  # Customization file
  customize: !include customize.yaml

#zones that get displayed in the map
zone:
  -name: homeZone
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 100

person:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/

# Example configuration.yaml entry for the Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

# Example configuration.yaml entry for the notifier
notify:
  - name: NOTIFIER_NAME
    platform: telegram
    chat_id: !secret telegram_chat_id

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

asuswrt:
  host: !secret router_ip
  username: !secret router_username
  password: !secret router_password
# Text to speech
tts:
  - platform: google

#rfxcomm 433 mhz transciever
rfxtrx:
  device: /dev/ttyUSB0

#vacuum cleaner
vacuum:
  - platform: xiaomi_miio
    host: 192.168.2.151
    token: !secret vacuum_token

#weather info
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    name: !secret darksky_location
    mode: daily

# igd upnp

#yeelight
light:
  - platform: yeelight
    devices:
      192.168.2.150:
        name: Studio
        model: color1

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

device_tracker:
  - platform: asuswrt
    host: 192.168.2.1
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false
  - platform: gpslogger
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false

#system health component
system_health:

# Cloud
cloud:

# Other files
sensor: !include sensors.yaml
switch: !include switches.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
